version: 0.0
os: linux
files:
   - source: /  
     destination: /home/ubuntu/MileStone3_App
hooks:
   BeforeInstall:
    - location: start.sh
      runas: root
   AfterInstall:
    - location: script.sh
      runas: root
